COOKIE: ENC[AES256_GCM,data:mW4epJcksR73HxGL2/WrNdd81dmux92uFDVsdTFhrRY7fXg3A+lhSVd74P+1FPBh4aW1z5jkj30t1rc5E699co/IW3U/jzcoQJKU5tB38y+mIrt6SwfWzrQJIafjfLbrKo0AK1V8cRE7Xtkh5iKttQKpj0uWmQkBiQOx1cGHL3I=,iv:hTK2gWyLX6PYCPbMnmjY08txs5FKi44BJ0KRVahlwRg=,tag:6QdNSlB249uVfqmbzH90Fg==,type:str]
sops:
    age:
        - recipient: age1cfd003wlk8w2hhtlwflyuc6lzwsswc48kpl9cafrg4kc5jp3u5rqckcf5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ0xLblk0WHZVWE91Yy9M
            Mk1mR1JFeFRrQVppVVN2dUR5bXJMVzR1UXdFCnlhajVNMFZTT051RzUyRGh5NDhZ
            dmpOemNiRU4rSzJpYWdkdHVLZkFacjAKLS0tIHFKY2E1ZzFiMlNrM1Q1WEtjRmU2
            ZGVvWDBpN3FsWTRkTUhrTy9aZ29qaTgKHsaDd+21ZpNFnVUh4X23Zdoe9g8rlcc8
            w31UUmJZ1XwHU6S2nCC89vmA70+rcowvnj1VAMArWIAeR8zudX4HEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:56:00Z"
    mac: ENC[AES256_GCM,data:OkH4ATuiYnfYB1kyj1DHp51mKGAEQOUiS6zr7X9HUlzs2QZFsvJTuFE+MuaXWDzU6a59/89N7+4e5rqEo8AYtzbSiONT3ISiUC8BQQ/q1N59jdmbu02sQ/IpBXUAHoE+znHKwtqLBnzJsGmYQhNmPHawuV1teT4EQc9crdMKFas=,iv:GQWbBFKaMUsZ8BhaFfkqo1SdtwUEIqZVJnQ5EyFBmWc=,tag:EcDlQIZTfdrB9YsazVgK5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.1
