COOKIE: ENC[AES256_GCM,data:wJHR4U6c5kMKB9ImqJpChg1FLmefUnCQDeuLsJo1GZdMzC/DSUBADqhFciA9mB/kTJK4WPZT7UZNtFcVtHS4kzVE6GFQffNGWRYQ70MfWIT2VDpWoL8wwWrMbvr0QHGp1zT9s89WOUUwTuTQ692UbEuWUidXTmSo9KvIdcrtkdk=,iv:k1Yg3IG1DizVjdI4sAFHFHCnOWG1gz03PmJiybNsgkA=,tag:A6rgaVvXP8RDNZWq14uMcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age102w4y6gsntvw93n590agqdg9v3tt8rs0x2kpunvu39jh6lyvdpeq7ct844
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvalhyRTAxbS9ZU21zS285
            c0grMW5BeUtWZHU2ZVVUUXBtNWhQb00rc2lrCnN3bWFyMEJtQ2hROEFVUU82S2JG
            N2VPZWJWemVvd0tvb1o2NE55dW54WEUKLS0tIFB6M0c0NVVCS1IxUEVhVERGeEtQ
            UGYrU1hraXEwK0htMFlWU3VVSE0xMDQKCxCEuR/x+4EiOYjBVRYLkA2kNki3fxpy
            3mSrANtIsjgrZOdpqoC8xWIzoSBPm28GIjpqn6cXIRIKjLe0zLicDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cfd003wlk8w2hhtlwflyuc6lzwsswc48kpl9cafrg4kc5jp3u5rqckcf5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ042WGp2S0h3MWxKeXlI
            ZFRpdG1DaTlGcm0xeWNYNkJOeksvdUx1MzA4CmZINE5IRS9BTFBLK0hoeXVmd2FM
            R3EzaHdGNE5TaEtjV1dLK1BYV0pYWFEKLS0tIG1kRTRKN0lVdG9ITmV5dW90TEN5
            MnczWUlWZEIzZllaRk5iWWNvTXdFdU0KEotLjfxxqSEiRYTvCeur7mQatWvYo83Q
            TlVcNTkf/qr78/x3gD69T8ujIHBwNG7PZWrOy0w9+POfUZ5y4Zu1bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T01:11:09Z"
    mac: ENC[AES256_GCM,data:etjMLKxhsFEuNvL/aCtP0/VoQUTedeGS2lKjYaJ9/e7Vn1ohXj2Jc2LJIrIXrsToddk3Kzo/ezYUB/jiXKQ/8aGqtCRA+eor3l1MeSInChJvadJqHEycW1zaAg8N4f3grrdt0TLPYrK5WfUM3sbDV+Ds+JCaW3+6p1wlN1bcZuo=,iv:6bQ8VHTCqouwbKf8AukTYazg+uTZqNJWKOoRAmylH3U=,tag:hngI+CdP5pYxnqpW7C/XBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
